### ISSUE TITLE
Expiration strategy doesn't work with module parameters

### ISSUE THREAD

**Issue by ezyang** [ezyang/pytorch-unattached#142]
```
    def test_retrace_model(self):
        class MyNet(nn.Module):
            def __init__(self):
                super(MyNet, self).__init__()
                self.hidden = nn.Parameter(torch.randn(2, 2))
            def forward(self, input):
                return input
        m = MyNet()
        x = Variable(torch.randn(1))
        trace, _ = torch.jit.record_trace(m, x)
        y = Variable(torch.randn(1))
        trace, _ = torch.jit.record_trace(m, y)
```

Fails with:

```
======================================================================
ERROR: test_retrace_model (__main__.TestJit)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test_jit.py", line 54, in test_retrace_model
    trace, _ = torch.jit.record_trace(m, y)
  File "/data/users/ezyang/pytorch/torch/jit.py", line 192, in record_trace
    args, parameters)
  File "/data/users/ezyang/pytorch/torch/jit.py", line 148, in record_trace
    self.saved_trace = torch._C._tracer_enter(trace_inputs)
RuntimeError: /data/users/ezyang/pytorch/torch/csrc/jit/tracer.h:167: enter: Assertion `input->tracing_state.state.expired()` failed.
```

I structured the example this way to avoid cries of "It's UB!" The code above is morally the same as this smaller repro:

```
    def test_retrace_model(self):
        def f(input):
            return input
        x = Variable(torch.randn(1))
        trace, _ = torch.jit.record_trace(f, x)
        trace, _ = torch.jit.record_trace(f, x)
```

And in case people may have forgotten, let me remind you of #57, which I claim would have solved this problem...

**Comment by apaszke** [comment]
There's another simple fix which doesn't involve TLS (I really don't like it in here because it can silently break in weird ways) - allow keeping multiple tracing states in a Variable

**Comment by ezyang** [comment]
@soumith has asked us to reduce the amount of TLS in PyTorch, so I don't think we are doing the TLS solution anytime soon...

**Comment by ezyang** [comment]
I think Adam's multiple tracing patch fixes this.
